language: node_js
sudo: false
dist: trusty
node_js:
- 'node'
branches:
  only:
  - master
  - dev
before_install:
- npm i -g npm@latest
- npm install -g @angular/cli@next
install:
- npm install
script:
- npm run build:dynamic
cache:
  directories:
  - "./node_modules"
addons:
  ssh_known_hosts: homework.cs.tufts.edu
before_deploy:
- openssl aes-256-cbc -K $encrypted_e276fd3f97f2_key -iv $encrypted_e276fd3f97f2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/ci/build-prod.sh
    on: master
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/ci/build-dev.sh
    on: dev
