language: node_js
sudo: false
dist: trusty
node_js:
- 'node'
branches:
  only:
  - master
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_e276fd3f97f2_key -iv $encrypted_e276fd3f97f2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- npm i -g npm@^5.0.1
- npm install -g @angular/cli
install:
- npm install
script:
- ng build --prod --output-path=public_html
cache:
  directories:
  - "$HOME/.npm"
deploy:
  - provider: script
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public_html $USER@$HOST:PROD_PATH/public_html
    on: master
  - provider: script
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public_html $USER@$HOST:DEV_PATH/public_html
    on: dev
